<XProtocol> 
{
  <ID> 1000001 
  <Userversion> 666.0 
  
  <ParamMap.""> 
  {
    <ParamMap."DMWL"> 
    {
      
      <ParamMap."Pause"> 
      {
        
        <ParamString."CodeValue">  { }
        <ParamString."CodingSchemeVersion">  { }
        <ParamString."CodingSchemeDesignator">  { }
        <ParamString."CodeMeaning">  { }
      }
      <ParamMap."Meas"> 
      {
        
        <ParamString."CodeValue">  { }
        <ParamString."CodingSchemeVersion">  { }
        <ParamString."CodingSchemeDesignator">  { }
        <ParamString."CodeMeaning">  { }
      }
    }
    <ParamMap."MultiStep"> 
    {
      
      <ParamBool."IsMultistep">  { }
      <ParamArray."SubStep"> 
      {
        <Default> <ParamLong.""> 
        {
        }
        { 1  }
        
      }
      <ParamBool."SaveNonnormalizedImages">  { "true"  }
      <ParamBool."IsInlineCompose">  { }
      <ParamLong."ComposingGroup">  { 1  }
      <ParamBool."IsLastStep">  { }
      <ParamChoice."ComposingFunction">  { <Limit> { "Angio" "Spine" "Adaptive" "Diffusion" } "Angio"  }
      <ParamChoice."ComposingNormalize">  { <Limit> { "Off" "Weak" "Medium" "Strong" } "Off"  }
      <ParamString."SeriesDescription">  { }
      <ParamLong."2DDistCor">  { }
      <ParamLong."DynDistCor">  { }
      <ParamLong."ScanAtCenterDummy">  { }
    }
    <ParamMap."OpenRecon"> 
    {
      
      <ParamString."OpenReconAlgorithm">  { }
      <ParamArray."Parameters"> 
      {
        <Default> <ParamMap.""> 
        {
          
          <ParamString."Id"> 
          {
          }
          
          <ParamString."ParameterValue"> 
          {
          }
        }
        { }
        { }
        { }
        { }
        { }
        { }
        { }
        { }
        { }
        { }
        { }
        { }
        { }
        { }
        
      }
    }
    <ParamMap."Properties"> 
    {
      
      <ParamMap."Reconstruction"> 
      {
        
        <ParamBool."recon_prio">  { }
      }
      <ParamMap."Sound"> 
      {
        
        <ParamString."PreSound">  { }
        <ParamString."PostSound">  { }
      }
      <ParamMap."AutoLoad"> 
      {
        
        <ParamBool."DisableAutoTransfer">  { }
        <ParamBool."AutoStore">  { "true"  }
        <ParamBool."LoadToFilming">  { "true"  }
        <ParamBool."LoadToViewer">  { "true"  }
        <ParamBool."LoadToStamp">  { }
        <ParamBool."LoadToGraphic">  { }
        <ParamChoice."GraphicSegmentChoice">  { <Limit> { "Default" "1st segment" "2nd segment" "3rd segment" "All segments" } "Default"  }
        <ParamBool."InlineMovie">  { }
        <ParamBool."AutoOpenInlineDisplay">  { }
        <ParamBool."AutoCloseInlineDisplay">  { }
        <ParamBool."InlinePositionDisplay">  { }
        <ParamChoice."InlinePositionDisplayOrientation">  { <Limit> { "All orientations" "Sag" "Cor" "Tra" } "All orientations"  }
      }
      <ParamMap."SlicePositioning"> 
      {
        
        <ParamBool."AutoAlignSpine">  { }
      }
      <ParamMap."Queue"> 
      {
        
        <ParamChoice."CoilSelectMode">  { <Limit> { "Default" "Auto Coil Select Off" "Auto Coil Select On" "Auto Coil Select No Spine" "Auto Coil Select Restricted" "Coil Memory Off" "Coil Memory On" "All Off" } "All Off"  }
        <ParamArray."CoilCompartments"> 
        {
          <Default> <ParamBool.""> 
          {
            <Visible> "true" 
            <Limit> { "true" "false" }
          }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          { }
          
        }
        <ParamBool."WorkingMan">  { }
        <ParamBool."WaitForUserToStart">  { }
        <ParamChoice."WaitForStartChoice">  { <Limit> { "Single measurement" "Repeated measurement" } "Single measurement"  }
        <ParamString."Description">  { }
        <ParamString."ProtocolName">  { "EP2D_QA_warm-up"  }
      }
    }
  }
}

<XProtocol> 
{
  
  <ParamMap.""> 
  {
    <ParamMap."Common"> 
    {
      
      <ParamBool."DisableVoiceCommands">  { }
      <ParamBool."IsRadialSliceSortingActive">  { }
      <ParamBool."ConfidenceRescaling">  { }
    }
    <ParamMap."ConflictSolving"> 
    {
      
      <ParamLong."ConflictSolvingMode">  { }
      <ParamDouble."MaxTr">  { }
      <ParamDouble."MinFlipAngle">  { }
    }
  }
}

### ASCCONV BEGIN object=MrProtDataImpl@MrProtocolData version=66110001 converter=%MEASCONST%/ConverterList/Prot_Converter.txt ###
ulVersion	 = 	66110001
tSequenceFileName	 = 	"%CustomerSeq%\ns_qa_ep2d_fid"
tProtocolName	 = 	"EP2D_QA_warm-up"
lScanRegionPosTra	 = 	0.0
ucScanRegionPosValid	 = 	0x1
lPtabAbsStartPosZ	 = 	0
bPtabAbsStartPosZValid	 = 	0x0
lContrasts	 = 	1
lCombinedEchoes	 = 	1
ucDisableChangeStoreImages	 = 	0x1
ucAAMode	 = 	1
ucAARegionMode	 = 	1
ucAARefMode	 = 	1
ucReconstructionMode	 = 	1
ucOneSeriesForAllMeas	 = 	1
ucPHAPSMode	 = 	1
ulWrapUpMagn	 = 	1
lAverages	 = 	1
dAveragesDouble	 = 	1.0
lRepetitions	 = 	199
lScanTimeSec	 = 	2
lTotalScanTimeSec	 = 	404
dRefSNR	 = 	205165.48199
dRefSNR_VOI	 = 	205165.48199
ulMotionCorr	 = 	1
ucCineMode	 = 	1
ucSequenceType	 = 	4
ucCoilCombineMode	 = 	1
ucFlipAngleMode	 = 	1
lTOM	 = 	1
ucReadOutMode	 = 	1
ucBold3dPace	 = 	1
ucTmapB0Correction	 = 	1
ucTmapEval	 = 	1
ucTmapImageType	 = 	1
ulOrganUnderExamination	 = 	1
dTissueT1	 = 	10.0
dTissueT2	 = 	5.0
lInvContrasts	 = 	1
ulReaquisitionMode	 = 	1
lDummyScans	 = 	0
ucExternalTriggerSignal	 = 	0x0
lSilentPeriod	 = 	0
dOverallImageScaleFactor	 = 	0.338512396694
dOverallImageScaleCorrectionFactor	 = 	1.0
dAutoCoilSelectIlluRangeScale	 = 	0.699999988079
SarOptimization	 = 	0
CameraBasedMotionCorrection	 = 	0
ucBreastApplication	 = 	0x0
ucEddyCurrentComp	 = 	0x0
ucStaticFieldCorrection	 = 	0x0
ucDenoiseUniform	 = 	0x0
ucUnfilteredImagesForDenoiseUniform	 = 	0x0
lDenoiseWeight	 = 	1
sInversionContrastCombination	 = 	1
ucMotionCorSAMEROrig	 = 	0x1
sProtConsistencyInfo.flNominalB0	 = 	2.89362001419
sGRADSPEC.ucMode	 = 	1
sGRADSPEC.ucNoiseReduction	 = 	1
sGRADSPEC.asGPAData.__attribute__.size	 = 	2
sGRADSPEC.asGPAData[0].sEddyCompensationX.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sEddyCompensationX.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sEddyCompensationY.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sEddyCompensationY.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sEddyCompensationZ.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sEddyCompensationZ.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sB0CompensationX.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sB0CompensationX.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sB0CompensationY.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sB0CompensationY.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sB0CompensationZ.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sB0CompensationZ.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationXY.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationXY.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationXZ.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationXZ.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationYX.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationYX.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationYZ.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationYZ.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationZX.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationZX.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationZY.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[0].sCrossTermCompensationZY.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sEddyCompensationX.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sEddyCompensationX.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sEddyCompensationY.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sEddyCompensationY.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sEddyCompensationZ.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sEddyCompensationZ.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sB0CompensationX.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sB0CompensationX.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sB0CompensationY.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sB0CompensationY.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sB0CompensationZ.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sB0CompensationZ.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationXY.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationXY.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationXZ.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationXZ.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationYX.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationYX.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationYZ.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationYZ.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationZX.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationZX.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationZY.aflAmplitude.__attribute__.size	 = 	5
sGRADSPEC.asGPAData[1].sCrossTermCompensationZY.aflTimeConstant.__attribute__.size	 = 	5
sGRADSPEC.alShimCurrent.__attribute__.size	 = 	15
sTXSPEC.lBCExcitationMode	 = 	0
sTXSPEC.lBCSeqExcitationMode	 = 	4
sTXSPEC.ucRFPulseType	 = 	2
sTXSPEC.ucExcitMode	 = 	32
sTXSPEC.ucSimultaneousExcitation	 = 	1
sTXSPEC.lB1ShimMode	 = 	1
sTXSPEC.asNucleusInfo.__attribute__.size	 = 	2
sTXSPEC.asNucleusInfo[0].tNucleus	 = 	"1H"
sTXSPEC.asNucleusInfo[0].lCoilSelectIndex	 = 	0
sTXSPEC.asNucleusInfo[0].CompProtectionValues.MaxOnlineTxAmpl.__attribute__.size	 = 	8
sTXSPEC.asNucleusInfo[0].CompProtectionValues.WorstCaseMaxOnlineTxAmpl.__attribute__.size	 = 	8
sTXSPEC.asNucleusInfo[0].CompProtectionValues.adGainVariationAvg.__attribute__.size	 = 	8
sTXSPEC.asNucleusInfo[0].CompProtectionValues.adGainVariationPeak.__attribute__.size	 = 	8
sTXSPEC.asNucleusInfo[0].CompProtectionValues.DecouplingMatrix.ComplexData.__attribute__.size	 = 	0
sTXSPEC.asNucleusInfo[0].CompProtectionValues.ZZMatrixVector.__attribute__.size	 = 	0
sTXSPEC.asNucleusInfo[0].CompProtectionValues.ScatterMatrix.ComplexData.__attribute__.size	 = 	0
sTXSPEC.asNucleusInfo[0].aTxScaleFactorSlice.__attribute__.size	 = 	0
sTXSPEC.asNucleusInfo[1].lCoilSelectIndex	 = 	-1
sTXSPEC.asNucleusInfo[1].CompProtectionValues.MaxOnlineTxAmpl.__attribute__.size	 = 	8
sTXSPEC.asNucleusInfo[1].CompProtectionValues.WorstCaseMaxOnlineTxAmpl.__attribute__.size	 = 	8
sTXSPEC.asNucleusInfo[1].CompProtectionValues.adGainVariationAvg.__attribute__.size	 = 	8
sTXSPEC.asNucleusInfo[1].CompProtectionValues.adGainVariationPeak.__attribute__.size	 = 	8
sTXSPEC.asNucleusInfo[1].CompProtectionValues.DecouplingMatrix.ComplexData.__attribute__.size	 = 	0
sTXSPEC.asNucleusInfo[1].CompProtectionValues.ZZMatrixVector.__attribute__.size	 = 	0
sTXSPEC.asNucleusInfo[1].CompProtectionValues.ScatterMatrix.ComplexData.__attribute__.size	 = 	0
sTXSPEC.asNucleusInfo[1].aTxScaleFactorSlice.__attribute__.size	 = 	0
sTXSPEC.aRFPULSE.__attribute__.size	 = 	256
sTXSPEC.aTxScaleFactor.__attribute__.size	 = 	8
sTXSPEC.aPTXRFPulse.__attribute__.size	 = 	0
sTXSPEC.B1CorrectionParameters.bValid	 = 	0x0
sTXSPEC.B1CorrectionParameters.bActive	 = 	0x0
sTXSPEC.B1CorrectionParameters.flCorrectionFactorMax	 = 	1.0
sTXSPEC.B1CorrectionParameters.flPeakReserveFactor	 = 	0.0
sRXSPEC.lSeqGain	 = 	1
sRXSPEC.UseDoubleDataRate	 = 	0x0
sRXSPEC.bPilotToneSupportActive	 = 	0x0
sRXSPEC.asNucleusInfo.__attribute__.size	 = 	2
sRXSPEC.asNucleusInfo[0].tNucleus	 = 	"1H"
sRXSPEC.asNucleusInfo[0].lCoilSelectIndex	 = 	0
sRXSPEC.asNucleusInfo[1].lCoilSelectIndex	 = 	-1
sRXSPEC.alVariCapVoltages.__attribute__.size	 = 	4
sRXSPEC.alDwellTime.__attribute__.size	 = 	256
sRXSPEC.alDwellTime[0]	 = 	4600
sRXSPEC.asLocalShimData.__attribute__.size	 = 	8
sAdjData.uiAdjFreMode	 = 	1
sAdjData.uiAdjTraMode	 = 	1
sAdjData.uiAdjShimMode	 = 	2
sAdjData.uiAdjWatSupMode	 = 	1
sAdjData.uiAdjRFMapMode	 = 	1
sAdjData.uiAdjMDSMode	 = 	1
sAdjData.uiAdjTableTolerance	 = 	2
sAdjData.uiAdjFreProtRelated	 = 	0x1
sAdjData.lCoupleAdjVolTo	 = 	1
sAdjData.uiAdjB0AcqMode	 = 	1
sAdjData.uiAdjB1AcqMode	 = 	1
sAdjData.uiAdjFreqConfirmSpec	 = 	1
sAdjData.uiAdjustmentMode	 = 	1
sAdjData.uiFastViewOptimization	 = 	1
sAdjData.bAdjustWithBreathhold	 = 	0x0
sAdjData.uiLocalShim	 = 	0
sAdjData.uiLRBalancing	 = 	0
sAdjData.sAdjUIOverrides.iAdjUIFieldMapMode	 = 	-1
sAdjData.sAdjUIOverrides.iAdjUITraMode	 = 	-1
alTR.__attribute__.size	 = 	256
alTR[0]	 = 	2000000
alTI.__attribute__.size	 = 	256
alTD.__attribute__.size	 = 	256
alTE.__attribute__.size	 = 	256
alTE[0]	 = 	26000
acFlowComp.__attribute__.size	 = 	256
acFlowComp[0]	 = 	1
sSliceArray.lSize	 = 	27
sSliceArray.lConc	 = 	1
sSliceArray.ucMode	 = 	4
sSliceArray.ucAnatomicalSliceMode	 = 	4
sSliceArray.ucConcatenationsSelectModeResp	 = 	1
sSliceArray.asSlice.__attribute__.size	 = 	256
sSliceArray.asSlice[0].dThickness	 = 	4.0
sSliceArray.asSlice[0].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[0].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[0].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[0].sPosition.dTra	 = 	-65.0
sSliceArray.asSlice[0].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[1].dThickness	 = 	4.0
sSliceArray.asSlice[1].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[1].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[1].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[1].sPosition.dTra	 = 	-60.0
sSliceArray.asSlice[1].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[2].dThickness	 = 	4.0
sSliceArray.asSlice[2].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[2].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[2].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[2].sPosition.dTra	 = 	-55.0
sSliceArray.asSlice[2].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[3].dThickness	 = 	4.0
sSliceArray.asSlice[3].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[3].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[3].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[3].sPosition.dTra	 = 	-50.0
sSliceArray.asSlice[3].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[4].dThickness	 = 	4.0
sSliceArray.asSlice[4].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[4].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[4].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[4].sPosition.dTra	 = 	-45.0
sSliceArray.asSlice[4].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[5].dThickness	 = 	4.0
sSliceArray.asSlice[5].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[5].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[5].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[5].sPosition.dTra	 = 	-40.0
sSliceArray.asSlice[5].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[6].dThickness	 = 	4.0
sSliceArray.asSlice[6].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[6].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[6].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[6].sPosition.dTra	 = 	-35.0
sSliceArray.asSlice[6].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[7].dThickness	 = 	4.0
sSliceArray.asSlice[7].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[7].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[7].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[7].sPosition.dTra	 = 	-30.0
sSliceArray.asSlice[7].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[8].dThickness	 = 	4.0
sSliceArray.asSlice[8].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[8].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[8].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[8].sPosition.dTra	 = 	-25.0
sSliceArray.asSlice[8].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[9].dThickness	 = 	4.0
sSliceArray.asSlice[9].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[9].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[9].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[9].sPosition.dTra	 = 	-20.0
sSliceArray.asSlice[9].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[10].dThickness	 = 	4.0
sSliceArray.asSlice[10].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[10].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[10].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[10].sPosition.dTra	 = 	-15.0
sSliceArray.asSlice[10].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[11].dThickness	 = 	4.0
sSliceArray.asSlice[11].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[11].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[11].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[11].sPosition.dTra	 = 	-10.0
sSliceArray.asSlice[11].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[12].dThickness	 = 	4.0
sSliceArray.asSlice[12].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[12].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[12].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[12].sPosition.dTra	 = 	-5.0
sSliceArray.asSlice[12].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[13].dThickness	 = 	4.0
sSliceArray.asSlice[13].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[13].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[13].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[13].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[14].dThickness	 = 	4.0
sSliceArray.asSlice[14].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[14].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[14].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[14].sPosition.dTra	 = 	5.0
sSliceArray.asSlice[14].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[15].dThickness	 = 	4.0
sSliceArray.asSlice[15].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[15].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[15].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[15].sPosition.dTra	 = 	10.0
sSliceArray.asSlice[15].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[16].dThickness	 = 	4.0
sSliceArray.asSlice[16].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[16].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[16].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[16].sPosition.dTra	 = 	15.0
sSliceArray.asSlice[16].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[17].dThickness	 = 	4.0
sSliceArray.asSlice[17].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[17].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[17].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[17].sPosition.dTra	 = 	20.0
sSliceArray.asSlice[17].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[18].dThickness	 = 	4.0
sSliceArray.asSlice[18].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[18].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[18].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[18].sPosition.dTra	 = 	25.0
sSliceArray.asSlice[18].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[19].dThickness	 = 	4.0
sSliceArray.asSlice[19].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[19].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[19].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[19].sPosition.dTra	 = 	30.0
sSliceArray.asSlice[19].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[20].dThickness	 = 	4.0
sSliceArray.asSlice[20].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[20].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[20].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[20].sPosition.dTra	 = 	35.0
sSliceArray.asSlice[20].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[21].dThickness	 = 	4.0
sSliceArray.asSlice[21].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[21].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[21].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[21].sPosition.dTra	 = 	40.0
sSliceArray.asSlice[21].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[22].dThickness	 = 	4.0
sSliceArray.asSlice[22].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[22].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[22].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[22].sPosition.dTra	 = 	45.0
sSliceArray.asSlice[22].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[23].dThickness	 = 	4.0
sSliceArray.asSlice[23].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[23].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[23].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[23].sPosition.dTra	 = 	50.0
sSliceArray.asSlice[23].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[24].dThickness	 = 	4.0
sSliceArray.asSlice[24].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[24].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[24].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[24].sPosition.dTra	 = 	55.0
sSliceArray.asSlice[24].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[25].dThickness	 = 	4.0
sSliceArray.asSlice[25].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[25].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[25].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[25].sPosition.dTra	 = 	60.0
sSliceArray.asSlice[25].sNormal.dTra	 = 	1.0
sSliceArray.asSlice[26].dThickness	 = 	4.0
sSliceArray.asSlice[26].dPhaseFOV	 = 	220.0
sSliceArray.asSlice[26].dReadoutFOV	 = 	220.0
sSliceArray.asSlice[26].sPosition.dCor	 = 	-20.0
sSliceArray.asSlice[26].sPosition.dTra	 = 	65.0
sSliceArray.asSlice[26].sNormal.dTra	 = 	1.0
sSliceArray.alSliceAcqOrder.__attribute__.size	 = 	256
sSliceArray.alSliceAcqOrder[1]	 = 	1
sSliceArray.alSliceAcqOrder[2]	 = 	2
sSliceArray.alSliceAcqOrder[3]	 = 	3
sSliceArray.alSliceAcqOrder[4]	 = 	4
sSliceArray.alSliceAcqOrder[5]	 = 	5
sSliceArray.alSliceAcqOrder[6]	 = 	6
sSliceArray.alSliceAcqOrder[7]	 = 	7
sSliceArray.alSliceAcqOrder[8]	 = 	8
sSliceArray.alSliceAcqOrder[9]	 = 	9
sSliceArray.alSliceAcqOrder[10]	 = 	10
sSliceArray.alSliceAcqOrder[11]	 = 	11
sSliceArray.alSliceAcqOrder[12]	 = 	12
sSliceArray.alSliceAcqOrder[13]	 = 	13
sSliceArray.alSliceAcqOrder[14]	 = 	14
sSliceArray.alSliceAcqOrder[15]	 = 	15
sSliceArray.alSliceAcqOrder[16]	 = 	16
sSliceArray.alSliceAcqOrder[17]	 = 	17
sSliceArray.alSliceAcqOrder[18]	 = 	18
sSliceArray.alSliceAcqOrder[19]	 = 	19
sSliceArray.alSliceAcqOrder[20]	 = 	20
sSliceArray.alSliceAcqOrder[21]	 = 	21
sSliceArray.alSliceAcqOrder[22]	 = 	22
sSliceArray.alSliceAcqOrder[23]	 = 	23
sSliceArray.alSliceAcqOrder[24]	 = 	24
sSliceArray.alSliceAcqOrder[25]	 = 	25
sSliceArray.alSliceAcqOrder[26]	 = 	26
sSliceArray.anAsc.__attribute__.size	 = 	256
sSliceArray.anAsc[1]	 = 	1
sSliceArray.anAsc[2]	 = 	2
sSliceArray.anAsc[3]	 = 	3
sSliceArray.anAsc[4]	 = 	4
sSliceArray.anAsc[5]	 = 	5
sSliceArray.anAsc[6]	 = 	6
sSliceArray.anAsc[7]	 = 	7
sSliceArray.anAsc[8]	 = 	8
sSliceArray.anAsc[9]	 = 	9
sSliceArray.anAsc[10]	 = 	10
sSliceArray.anAsc[11]	 = 	11
sSliceArray.anAsc[12]	 = 	12
sSliceArray.anAsc[13]	 = 	13
sSliceArray.anAsc[14]	 = 	14
sSliceArray.anAsc[15]	 = 	15
sSliceArray.anAsc[16]	 = 	16
sSliceArray.anAsc[17]	 = 	17
sSliceArray.anAsc[18]	 = 	18
sSliceArray.anAsc[19]	 = 	19
sSliceArray.anAsc[20]	 = 	20
sSliceArray.anAsc[21]	 = 	21
sSliceArray.anAsc[22]	 = 	22
sSliceArray.anAsc[23]	 = 	23
sSliceArray.anAsc[24]	 = 	24
sSliceArray.anAsc[25]	 = 	25
sSliceArray.anAsc[26]	 = 	26
sSliceArray.anPos.__attribute__.size	 = 	256
sSliceArray.anPos[1]	 = 	1
sSliceArray.anPos[2]	 = 	2
sSliceArray.anPos[3]	 = 	3
sSliceArray.anPos[4]	 = 	4
sSliceArray.anPos[5]	 = 	5
sSliceArray.anPos[6]	 = 	6
sSliceArray.anPos[7]	 = 	7
sSliceArray.anPos[8]	 = 	8
sSliceArray.anPos[9]	 = 	9
sSliceArray.anPos[10]	 = 	10
sSliceArray.anPos[11]	 = 	11
sSliceArray.anPos[12]	 = 	12
sSliceArray.anPos[13]	 = 	13
sSliceArray.anPos[14]	 = 	14
sSliceArray.anPos[15]	 = 	15
sSliceArray.anPos[16]	 = 	16
sSliceArray.anPos[17]	 = 	17
sSliceArray.anPos[18]	 = 	18
sSliceArray.anPos[19]	 = 	19
sSliceArray.anPos[20]	 = 	20
sSliceArray.anPos[21]	 = 	21
sSliceArray.anPos[22]	 = 	22
sSliceArray.anPos[23]	 = 	23
sSliceArray.anPos[24]	 = 	24
sSliceArray.anPos[25]	 = 	25
sSliceArray.anPos[26]	 = 	26
sSliceArray.sTSat.dThickness	 = 	50.0
sSliceArray.sTSat.ulShape	 = 	1
sGroupArray.lSize	 = 	1
sGroupArray.asGroup.__attribute__.size	 = 	256
sGroupArray.asGroup[0].nSize	 = 	27
sGroupArray.asGroup[0].dDistFact	 = 	0.25
sGroupArray.anMember.__attribute__.size	 = 	258
sGroupArray.anMember[1]	 = 	1
sGroupArray.anMember[2]	 = 	2
sGroupArray.anMember[3]	 = 	3
sGroupArray.anMember[4]	 = 	4
sGroupArray.anMember[5]	 = 	5
sGroupArray.anMember[6]	 = 	6
sGroupArray.anMember[7]	 = 	7
sGroupArray.anMember[8]	 = 	8
sGroupArray.anMember[9]	 = 	9
sGroupArray.anMember[10]	 = 	10
sGroupArray.anMember[11]	 = 	11
sGroupArray.anMember[12]	 = 	12
sGroupArray.anMember[13]	 = 	13
sGroupArray.anMember[14]	 = 	14
sGroupArray.anMember[15]	 = 	15
sGroupArray.anMember[16]	 = 	16
sGroupArray.anMember[17]	 = 	17
sGroupArray.anMember[18]	 = 	18
sGroupArray.anMember[19]	 = 	19
sGroupArray.anMember[20]	 = 	20
sGroupArray.anMember[21]	 = 	21
sGroupArray.anMember[22]	 = 	22
sGroupArray.anMember[23]	 = 	23
sGroupArray.anMember[24]	 = 	24
sGroupArray.anMember[25]	 = 	25
sGroupArray.anMember[26]	 = 	26
sGroupArray.anMember[27]	 = 	-1
sGroupArray.sPSat.dThickness	 = 	50.0
sGroupArray.sPSat.dGap	 = 	10.0
sGroupArray.sPSat.ulShape	 = 	1
sRSatArray.asElm.__attribute__.size	 = 	8
sRSatArray.asElm[0].ulShape	 = 	1
sRSatArray.asElm[1].ulShape	 = 	1
sRSatArray.asElm[2].ulShape	 = 	1
sRSatArray.asElm[3].ulShape	 = 	1
sRSatArray.asElm[4].ulShape	 = 	1
sRSatArray.asElm[5].ulShape	 = 	1
sRSatArray.asElm[6].ulShape	 = 	1
sRSatArray.asElm[7].ulShape	 = 	1
sNavigatorArray.asElm.__attribute__.size	 = 	5
sAutoAlign.dAAMatrix.__attribute__.size	 = 	16
sAutoAlign.dAAMatrix[0]	 = 	1.0
sAutoAlign.dAAMatrix[5]	 = 	1.0
sAutoAlign.dAAMatrix[10]	 = 	1.0
sAutoAlign.dAAMatrix[15]	 = 	1.0
sNavigatorPara.lBreathHoldMeas	 = 	1
sNavigatorPara.lRespComp	 = 	4
sNavigatorPara.dMinimumTriggerLevel	 = 	20.0
sNavigatorPara.adTrackingFactor.__attribute__.size	 = 	2
sNavigatorPara.adAcceptWindow.__attribute__.size	 = 	2
sNavigatorPara.adAcceptPosition.__attribute__.size	 = 	2
sNavigatorPara.adSearchWindow.__attribute__.size	 = 	2
sNavigatorPara.alFree.__attribute__.size	 = 	36
sNavigatorPara.adFree.__attribute__.size	 = 	24
sNavigatorPara.tFree.__attribute__.size	 = 	128
sBladePara.dBladeCoverage	 = 	100.0
sBladePara.ulMotionCorr	 = 	2
sBladePara.alFree.__attribute__.size	 = 	16
sBladePara.adFree.__attribute__.size	 = 	8
sPrepPulses.ucInversion	 = 	4
sPrepPulses.ucSatRecovery	 = 	1
sPrepPulses.ucT2Prep	 = 	1
sPrepPulses.ucTIScout	 = 	1
sPrepPulses.lMTCMode	 = 	1
sPrepPulses.lFlowAttenuation	 = 	1
sPrepPulses.ucFatSatMode	 = 	2
sPrepPulses.dDarkBloodThickness	 = 	200.0
sPrepPulses.dDarkBloodFlipAngle	 = 	200.0
sPrepPulses.dIRPulseThicknessFactor	 = 	0.77
sPrepPulses.ucBloodSuppression	 = 	1
sPrepPulses.lPhaseCorrectionMode	 = 	1
sPrepPulses.ucIRScheme	 = 	1
sPrepPulses.lFatSupOpt	 = 	1
sPrepPulses.lFatWaterContrast	 = 	1
sPrepPulses.adT2PrepDuration.__attribute__.size	 = 	1
sPrepPulses.adT2PrepDuration[0]	 = 	40.0
sKSpace.dPhaseResolution	 = 	1.0
sKSpace.dSliceResolution	 = 	1.0
sKSpace.dAngioDynCentralRegionA	 = 	20.0
sKSpace.dAngioDynSamplingDensityB	 = 	25.0
sKSpace.dSeqPhasePartialFourierForSNR	 = 	1.0
sKSpace.lBaseResolution	 = 	64
sKSpace.lPhaseEncodingLines	 = 	64
sKSpace.lPartitions	 = 	64
sKSpace.lImagesPerSlab	 = 	64
sKSpace.lRadialViews	 = 	64
sKSpace.lRadialInterleavesPerImage	 = 	1
sKSpace.lLinesPerShot	 = 	1
sKSpace.unReordering	 = 	1
sKSpace.ucPhasePartialFourier	 = 	16
sKSpace.ucSlicePartialFourier	 = 	16
sKSpace.ucAveragingMode	 = 	2
sKSpace.ucMultiSliceMode	 = 	2
sKSpace.ucDimension	 = 	2
sKSpace.ucTrajectory	 = 	1
sKSpace.lNumberOfBins	 = 	0
sKSpace.ucAsymmetricEchoMode	 = 	1
sKSpace.ucPOCS	 = 	1
sKSpace.Reordering3D	 = 	1
sKSpace.ucReadoutPartialFourier	 = 	16
sKSpace.ucDynamicMode	 = 	1
sKSpace.ucUndersamplingPattern	 = 	1
sKSpace.lTrajectoryOptimization	 = 	0
sKSpace.DistributionAsymmetry	 = 	0
sKSpace.SpiralInterleaves	 = 	1
sKSpace.PhaseEncOrder	 = 	0
sFastImaging.lEPIFactor	 = 	128
sFastImaging.lTurboFactor	 = 	1
sFastImaging.lSliceTurboFactor	 = 	1
sFastImaging.lSegments	 = 	1
sFastImaging.ucPhaseEncRE	 = 	0x0
sFastImaging.ucSegmentationMode	 = 	1
sFastImaging.lShots	 = 	1
sFastImaging.lEchoTrainDuration	 = 	700
sPhysioImaging.lSignal1	 = 	1
sPhysioImaging.lMethod1	 = 	1
sPhysioImaging.lSignal2	 = 	1
sPhysioImaging.lMethod2	 = 	1
sPhysioImaging.lPhases	 = 	1
sPhysioImaging.lRetroGatedImages	 = 	16
sPhysioImaging.lDummyHeartbeats	 = 	0
sPhysioImaging.sPhysioECG.lTriggerPulses	 = 	1
sPhysioImaging.sPhysioECG.lTriggerWindow	 = 	5
sPhysioImaging.sPhysioECG.lArrhythmiaDetection	 = 	1
sPhysioImaging.sPhysioECG.lCardiacGateOnThreshold	 = 	100000
sPhysioImaging.sPhysioECG.lCardiacGateOffThreshold	 = 	700000
sPhysioImaging.sPhysioECG.lTriggerIntervals	 = 	1
sPhysioImaging.sPhysioECG.lAcquisitionPosition	 = 	1
sPhysioImaging.sPhysioPulse.lTriggerPulses	 = 	1
sPhysioImaging.sPhysioPulse.lTriggerWindow	 = 	5
sPhysioImaging.sPhysioPulse.lArrhythmiaDetection	 = 	1
sPhysioImaging.sPhysioPulse.lCardiacGateOnThreshold	 = 	100000
sPhysioImaging.sPhysioPulse.lCardiacGateOffThreshold	 = 	700000
sPhysioImaging.sPhysioPulse.lTriggerIntervals	 = 	1
sPhysioImaging.sPhysioPulse.lAcquisitionPosition	 = 	1
sPhysioImaging.sPhysioExt.lTriggerPulses	 = 	1
sPhysioImaging.sPhysioExt.lTriggerWindow	 = 	5
sPhysioImaging.sPhysioExt.lArrhythmiaDetection	 = 	1
sPhysioImaging.sPhysioExt.lCardiacGateOnThreshold	 = 	100000
sPhysioImaging.sPhysioExt.lCardiacGateOffThreshold	 = 	700000
sPhysioImaging.sPhysioExt.lTriggerIntervals	 = 	1
sPhysioImaging.sPhysioExt.lAcquisitionPosition	 = 	1
sPhysioImaging.sPhysioExt2.lTriggerIntervals	 = 	1
sPhysioImaging.sPhysioExt2.lAcquisitionPosition	 = 	1
sPhysioImaging.sPhysioBeatSensor.lTriggerPulses	 = 	1
sPhysioImaging.sPhysioBeatSensor.lTriggerWindow	 = 	5
sPhysioImaging.sPhysioBeatSensor.lArrhythmiaDetection	 = 	1
sPhysioImaging.sPhysioBeatSensor.lCardiacGateOnThreshold	 = 	100000
sPhysioImaging.sPhysioBeatSensor.lCardiacGateOffThreshold	 = 	700000
sPhysioImaging.sPhysioBeatSensor.lTriggerIntervals	 = 	1
sPhysioImaging.sPhysioBeatSensor.lAcquisitionPosition	 = 	1
sPhysioImaging.sPhysioResp.lRespGateThreshold	 = 	20
sPhysioImaging.sPhysioResp.lRespGatePhase	 = 	2
sPhysioImaging.sPhysioResp.dGatingRatio	 = 	0.3
sPhysioImaging.sPhysioNative.ucMode	 = 	1
sPhysioImaging.sPhysioNative.ucFlowSenMode	 = 	1
sSpecPara.lPhaseCyclingType	 = 	1
sSpecPara.lPhaseEncodingType	 = 	1
sSpecPara.lRFExcitationBandwidth	 = 	1
sSpecPara.ucRemoveOversampling	 = 	0x1
sSpecPara.lAutoRefScanMode	 = 	1
sSpecPara.lAutoRefScanNo	 = 	1
sSpecPara.lDecouplingType	 = 	1
sSpecPara.lNOEType	 = 	1
sSpecPara.lExcitationType	 = 	1
sSpecPara.lSpecAppl	 = 	1
sSpecPara.lSpectralSuppression	 = 	1
sDiffusion.ulMode	 = 	1
sDiffusion.dsScheme	 = 	1
sDiffusion.ulQSpaceCoverage	 = 	1
sDiffusion.ulQSpaceSampling	 = 	1
sDiffusion.lQSpaceSteps	 = 	1
sDiffusion.alBValue.__attribute__.size	 = 	128
sDiffusion.alAverages.__attribute__.size	 = 	128
sDiffusion.sFreeDiffusionData.ulCoordinateSystem	 = 	1
sDiffusion.sFreeDiffusionData.ulNormalization	 = 	1
sDiffusion.sFreeDiffusionData.asDiffDirVector.__attribute__.size	 = 	0
sAngio.ucPCFlowMode	 = 	2
sAngio.ucTOFInflow	 = 	4
sAngio.lDynamicReconMode	 = 	1
sAngio.lTemporalInterpolation	 = 	1
sAngio.sFlowArray.asElm.__attribute__.size	 = 	16
sPreScanNormalizeFilter.ucMode	 = 	2
sDistortionCorrFilter.ucMode	 = 	1
sNoiseDecorrData.lNoiseDecorrDefaultMode	 = 	4
sPat.lAccelFactPE	 = 	1
sPat.lAccelFact3D	 = 	1
sPat.ucPATMode	 = 	1
sPat.ucRefScanMode	 = 	1
sPat.ucTPatAverageAllFrames	 = 	0x1
sPat.ulCaipirinhaMode	 = 	1
sPat.lAccelFactPeriph	 = 	16
sPat.lAccelFactCenter	 = 	3
sPat.lAccelFactorEcho	 = 	1
sPat.dTotalAccelFact	 = 	1.0
sMds.ulMdsModeMask	 = 	1
sMds.lTableSpeedNumerator	 = 	1
sMds.lmdsLinesPerSegment	 = 	15
sMds.lMdsPtabAbsStartPosZ	 = 	0
sMds.bMdsPtabAbsStartPosZValid	 = 	0x0
sMds.lMdsPtabAbsEndPosZ	 = 	0
sMds.bMdsPtabAbsEndPosZValid	 = 	0x0
sMds.lMdsPtabAbsStartPosZOriginal	 = 	0
sMds.lMdsPtabAbsEndPosZOriginal	 = 	0
sMds.dMdsRangeExtension	 = 	600.0
sMds.lSweeps	 = 	1
sMds.ucSweepMode	 = 	1
sMds.dDCSIlluminationScale	 = 	2.0
sMds.ucExcitDir	 = 	1
sMds.ucFreqShimPerSlice	 = 	0x1
sMds.ucSliceFollowing	 = 	0x1
sMds.ucDynamicCoilSwitching	 = 	0x1
sMds.ucPhaseNav	 = 	0x0
sMds.asMdsMotionInterval.__attribute__.size	 = 	8
sMds.alFree.__attribute__.size	 = 	8
sMds.adFree.__attribute__.size	 = 	8
sMds.sMdsEndPosSBCS_mm.dTra	 = 	600.0
sMds.sMdsPreScanNormalize.ucMode	 = 	2
sMds.sMdsPreScanNormalize.ucStackMode	 = 	4
sMds.sMdsPreScanNormalize.lNPELin	 = 	18
sAAInitialOffset.Laterality	 = 	0
sAAInitialOffset.SliceInformation.sPosition.dCor	 = 	-20.0
sAAInitialOffset.SliceInformation.sNormal.dTra	 = 	1.0
alRepetitionsDelayTimeMs.__attribute__.size	 = 	64
adFlipAngleDegree.__attribute__.size	 = 	32
adFlipAngleDegree[0]	 = 	90.0
aulServicePara.__attribute__.size	 = 	5
uiPerProxy2Skip.__attribute__.size	 = 	2
sCoilSelectMeas.sCoilStringForConversion	 = 	"HC1-7;NC1,2"
sCoilSelectMeas.aRxCoilSelectData.__attribute__.size	 = 	2
sCoilSelectMeas.aRxCoilSelectData[0].tNucleus	 = 	"1H"
sCoilSelectMeas.aRxCoilSelectData[0].iUsedRFactor	 = 	3
sCoilSelectMeas.aRxCoilSelectData[0].IgnoreCoilGroups	 = 	0x0
sCoilSelectMeas.aRxCoilSelectData[0].BCCombineMode	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].bSuppressMandatoryProperties	 = 	0x0
sCoilSelectMeas.aRxCoilSelectData[0].bIgnoreBCLCExcluding	 = 	0x0
sCoilSelectMeas.aRxCoilSelectData[0].bSuppressExclusiveProperties	 = 	0x0
sCoilSelectMeas.aRxCoilSelectData[0].tCheckUUID	 = 	"c219b3833208c8ed5f4be753193997f2a62694a5"
sCoilSelectMeas.aRxCoilSelectData[0].BCCombineMatrix.__attribute__.size	 = 	0
sCoilSelectMeas.aRxCoilSelectData[0].asList.__attribute__.size	 = 	64
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].lMuxChannelConnected	 = 	57
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].lRxChannelConnected	 = 	21
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].lADCChannelConnected	 = 	42
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].sCoilElementID.tElement	 = 	"N20"
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].sCoilElementID.ulUniqueKey	 = 	-933437288
sCoilSelectMeas.aRxCoilSelectData[0].asList[0].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].lMuxChannelConnected	 = 	57
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].lRxChannelConnected	 = 	21
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].lADCChannelConnected	 = 	41
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].sCoilElementID.tElement	 = 	"N21"
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].sCoilElementID.ulUniqueKey	 = 	-180565720
sCoilSelectMeas.aRxCoilSelectData[0].asList[1].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].lMuxChannelConnected	 = 	58
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].lRxChannelConnected	 = 	22
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].lADCChannelConnected	 = 	44
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].sCoilElementID.tElement	 = 	"N22"
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].sCoilElementID.ulUniqueKey	 = 	-1298353160
sCoilSelectMeas.aRxCoilSelectData[0].asList[2].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].lMuxChannelConnected	 = 	58
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].lRxChannelConnected	 = 	22
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].lADCChannelConnected	 = 	43
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].sCoilElementID.tElement	 = 	"N23"
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].sCoilElementID.ulUniqueKey	 = 	-1879270840
sCoilSelectMeas.aRxCoilSelectData[0].asList[3].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].lMuxChannelConnected	 = 	70
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].lRxChannelConnected	 = 	32
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].lADCChannelConnected	 = 	64
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].sCoilElementID.tElement	 = 	"N24"
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].sCoilElementID.ulUniqueKey	 = 	1037846104
sCoilSelectMeas.aRxCoilSelectData[0].asList[4].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].lMuxChannelConnected	 = 	70
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].lRxChannelConnected	 = 	32
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].lADCChannelConnected	 = 	63
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].sCoilElementID.tElement	 = 	"N25"
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].sCoilElementID.ulUniqueKey	 = 	12349416
sCoilSelectMeas.aRxCoilSelectData[0].asList[5].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].lMuxChannelConnected	 = 	69
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].lRxChannelConnected	 = 	31
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].lADCChannelConnected	 = 	62
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].sCoilElementID.tElement	 = 	"H87"
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].sCoilElementID.ulUniqueKey	 = 	-1204344108
sCoilSelectMeas.aRxCoilSelectData[0].asList[6].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].lMuxChannelConnected	 = 	55
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].lRxChannelConnected	 = 	19
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].lADCChannelConnected	 = 	37
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].sCoilElementID.tElement	 = 	"H80"
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].sCoilElementID.ulUniqueKey	 = 	169342660
sCoilSelectMeas.aRxCoilSelectData[0].asList[7].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].lMuxChannelConnected	 = 	55
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].lRxChannelConnected	 = 	19
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].lADCChannelConnected	 = 	38
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].sCoilElementID.tElement	 = 	"H81"
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].sCoilElementID.ulUniqueKey	 = 	930602868
sCoilSelectMeas.aRxCoilSelectData[0].asList[8].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].lMuxChannelConnected	 = 	56
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].lRxChannelConnected	 = 	20
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].lADCChannelConnected	 = 	40
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].sCoilElementID.tElement	 = 	"H82"
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].sCoilElementID.ulUniqueKey	 = 	1893180836
sCoilSelectMeas.aRxCoilSelectData[0].asList[9].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].lMuxChannelConnected	 = 	56
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].lRxChannelConnected	 = 	20
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].lADCChannelConnected	 = 	39
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].sCoilElementID.tElement	 = 	"H83"
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].sCoilElementID.ulUniqueKey	 = 	1303874580
sCoilSelectMeas.aRxCoilSelectData[0].asList[10].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].lMuxChannelConnected	 = 	68
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].lRxChannelConnected	 = 	30
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].lADCChannelConnected	 = 	60
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].sCoilElementID.tElement	 = 	"H84"
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].sCoilElementID.ulUniqueKey	 = 	-6860796
sCoilSelectMeas.aRxCoilSelectData[0].asList[11].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].lMuxChannelConnected	 = 	68
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].lRxChannelConnected	 = 	30
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].lADCChannelConnected	 = 	59
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].sCoilElementID.tElement	 = 	"H85"
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].sCoilElementID.ulUniqueKey	 = 	-1023968844
sCoilSelectMeas.aRxCoilSelectData[0].asList[12].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].lMuxChannelConnected	 = 	69
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].lRxChannelConnected	 = 	31
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].lADCChannelConnected	 = 	61
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].sCoilElementID.tElement	 = 	"H86"
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].sCoilElementID.ulUniqueKey	 = 	-2057895068
sCoilSelectMeas.aRxCoilSelectData[0].asList[13].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].lMuxChannelConnected	 = 	24
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].lRxChannelConnected	 = 	12
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].lADCChannelConnected	 = 	24
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].sCoilElementID.tElement	 = 	"N12"
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].sCoilElementID.ulUniqueKey	 = 	872989014
sCoilSelectMeas.aRxCoilSelectData[0].asList[14].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].lMuxChannelConnected	 = 	22
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].lRxChannelConnected	 = 	10
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].lADCChannelConnected	 = 	20
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].sCoilElementID.tElement	 = 	"N30"
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].sCoilElementID.ulUniqueKey	 = 	50344765
sCoilSelectMeas.aRxCoilSelectData[0].asList[15].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].lMuxChannelConnected	 = 	22
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].lRxChannelConnected	 = 	10
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].lADCChannelConnected	 = 	19
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].sCoilElementID.tElement	 = 	"N10"
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].sCoilElementID.ulUniqueKey	 = 	1321767478
sCoilSelectMeas.aRxCoilSelectData[0].asList[16].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].lMuxChannelConnected	 = 	23
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].lRxChannelConnected	 = 	11
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].lADCChannelConnected	 = 	22
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].sCoilElementID.tElement	 = 	"N31"
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].sCoilElementID.ulUniqueKey	 = 	1046485645
sCoilSelectMeas.aRxCoilSelectData[0].asList[17].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].lMuxChannelConnected	 = 	23
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].lRxChannelConnected	 = 	11
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].lADCChannelConnected	 = 	21
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].sCoilElementID.tElement	 = 	"N11"
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].sCoilElementID.ulUniqueKey	 = 	1940437894
sCoilSelectMeas.aRxCoilSelectData[0].asList[18].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].lMuxChannelConnected	 = 	24
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].lRxChannelConnected	 = 	12
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].lADCChannelConnected	 = 	23
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].sCoilElementID.tElement	 = 	"N32"
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].sCoilElementID.ulUniqueKey	 = 	2042650717
sCoilSelectMeas.aRxCoilSelectData[0].asList[19].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].lMuxChannelConnected	 = 	14
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].lRxChannelConnected	 = 	2
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].lADCChannelConnected	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].sCoilElementID.tElement	 = 	"H13"
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].sCoilElementID.ulUniqueKey	 = 	1790500316
sCoilSelectMeas.aRxCoilSelectData[0].asList[20].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].lMuxChannelConnected	 = 	13
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].lRxChannelConnected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].lADCChannelConnected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].sCoilElementID.tElement	 = 	"H10"
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].sCoilElementID.ulUniqueKey	 = 	756590348
sCoilSelectMeas.aRxCoilSelectData[0].asList[21].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].lMuxChannelConnected	 = 	13
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].lRxChannelConnected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].lADCChannelConnected	 = 	2
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].sCoilElementID.tElement	 = 	"H11"
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].sCoilElementID.ulUniqueKey	 = 	276336316
sCoilSelectMeas.aRxCoilSelectData[0].asList[22].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].lMuxChannelConnected	 = 	14
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].lRxChannelConnected	 = 	2
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].lADCChannelConnected	 = 	3
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].sCoilElementID.tElement	 = 	"H12"
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].sCoilElementID.ulUniqueKey	 = 	1473836140
sCoilSelectMeas.aRxCoilSelectData[0].asList[23].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].lMuxChannelConnected	 = 	61
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].lRxChannelConnected	 = 	23
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].lADCChannelConnected	 = 	46
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].sCoilElementID.tElement	 = 	"H25"
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].sCoilElementID.ulUniqueKey	 = 	1668045522
sCoilSelectMeas.aRxCoilSelectData[0].asList[24].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].lMuxChannelConnected	 = 	49
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].lRxChannelConnected	 = 	13
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].lADCChannelConnected	 = 	25
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].sCoilElementID.tElement	 = 	"H20"
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].sCoilElementID.ulUniqueKey	 = 	-1416833630
sCoilSelectMeas.aRxCoilSelectData[0].asList[25].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].lMuxChannelConnected	 = 	49
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].lRxChannelConnected	 = 	13
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].lADCChannelConnected	 = 	26
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].sCoilElementID.tElement	 = 	"H21"
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].sCoilElementID.ulUniqueKey	 = 	-1762853870
sCoilSelectMeas.aRxCoilSelectData[0].asList[26].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].lMuxChannelConnected	 = 	50
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].lRxChannelConnected	 = 	14
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].lADCChannelConnected	 = 	27
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].sCoilElementID.tElement	 = 	"H22"
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].sCoilElementID.ulUniqueKey	 = 	-783513918
sCoilSelectMeas.aRxCoilSelectData[0].asList[27].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].lMuxChannelConnected	 = 	50
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].lRxChannelConnected	 = 	14
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].lADCChannelConnected	 = 	28
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].sCoilElementID.tElement	 = 	"H23"
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].sCoilElementID.ulUniqueKey	 = 	-332615822
sCoilSelectMeas.aRxCoilSelectData[0].asList[28].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].lMuxChannelConnected	 = 	61
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].lRxChannelConnected	 = 	23
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].lADCChannelConnected	 = 	45
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].sCoilElementID.tElement	 = 	"H24"
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].sCoilElementID.ulUniqueKey	 = 	1577874274
sCoilSelectMeas.aRxCoilSelectData[0].asList[29].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].lMuxChannelConnected	 = 	66
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].lRxChannelConnected	 = 	28
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].lADCChannelConnected	 = 	56
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].sCoilElementID.tElement	 = 	"H66"
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].sCoilElementID.ulUniqueKey	 = 	-1084399084
sCoilSelectMeas.aRxCoilSelectData[0].asList[30].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].lMuxChannelConnected	 = 	53
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].lRxChannelConnected	 = 	17
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].lADCChannelConnected	 = 	34
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].sCoilElementID.tElement	 = 	"H60"
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].sCoilElementID.ulUniqueKey	 = 	807245748
sCoilSelectMeas.aRxCoilSelectData[0].asList[31].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].lMuxChannelConnected	 = 	53
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].lRxChannelConnected	 = 	17
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].lADCChannelConnected	 = 	33
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].sCoilElementID.tElement	 = 	"H61"
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].sCoilElementID.ulUniqueKey	 = 	226344452
sCoilSelectMeas.aRxCoilSelectData[0].asList[32].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].lMuxChannelConnected	 = 	54
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].lRxChannelConnected	 = 	18
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].lADCChannelConnected	 = 	36
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].sCoilElementID.tElement	 = 	"H62"
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].sCoilElementID.ulUniqueKey	 = 	1256047828
sCoilSelectMeas.aRxCoilSelectData[0].asList[33].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].lMuxChannelConnected	 = 	54
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].lRxChannelConnected	 = 	18
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].lADCChannelConnected	 = 	35
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].sCoilElementID.tElement	 = 	"H63"
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].sCoilElementID.ulUniqueKey	 = 	2008935780
sCoilSelectMeas.aRxCoilSelectData[0].asList[34].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].lMuxChannelConnected	 = 	65
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].lRxChannelConnected	 = 	27
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].lADCChannelConnected	 = 	54
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].sCoilElementID.tElement	 = 	"H64"
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].sCoilElementID.ulUniqueKey	 = 	-979553932
sCoilSelectMeas.aRxCoilSelectData[0].asList[35].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].lMuxChannelConnected	 = 	65
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].lRxChannelConnected	 = 	27
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].lADCChannelConnected	 = 	53
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].sCoilElementID.tElement	 = 	"H65"
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].sCoilElementID.ulUniqueKey	 = 	-117630780
sCoilSelectMeas.aRxCoilSelectData[0].asList[36].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].lMuxChannelConnected	 = 	66
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].lRxChannelConnected	 = 	28
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].lADCChannelConnected	 = 	55
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].sCoilElementID.tElement	 = 	"H67"
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].sCoilElementID.ulUniqueKey	 = 	-2109912156
sCoilSelectMeas.aRxCoilSelectData[0].asList[37].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].lMuxChannelConnected	 = 	67
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].lRxChannelConnected	 = 	29
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].lADCChannelConnected	 = 	58
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].sCoilElementID.tElement	 = 	"H68"
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].sCoilElementID.ulUniqueKey	 = 	7199861
sCoilSelectMeas.aRxCoilSelectData[0].asList[38].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].lMuxChannelConnected	 = 	67
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].lRxChannelConnected	 = 	29
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].lADCChannelConnected	 = 	57
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].sCoilElementID.tElement	 = 	"H69"
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].sCoilElementID.ulUniqueKey	 = 	1024325061
sCoilSelectMeas.aRxCoilSelectData[0].asList[39].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].lMuxChannelConnected	 = 	21
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].lRxChannelConnected	 = 	9
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].lADCChannelConnected	 = 	18
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].sCoilElementID.tElement	 = 	"H55"
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].sCoilElementID.ulUniqueKey	 = 	2120837738
sCoilSelectMeas.aRxCoilSelectData[0].asList[40].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].lMuxChannelConnected	 = 	18
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].lRxChannelConnected	 = 	6
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].lADCChannelConnected	 = 	12
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].sCoilElementID.tElement	 = 	"H51"
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].sCoilElementID.ulUniqueKey	 = 	-1947611990
sCoilSelectMeas.aRxCoilSelectData[0].asList[41].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].lMuxChannelConnected	 = 	18
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].lRxChannelConnected	 = 	6
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].lADCChannelConnected	 = 	11
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].sCoilElementID.tElement	 = 	"H52"
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].sCoilElementID.ulUniqueKey	 = 	-867584390
sCoilSelectMeas.aRxCoilSelectData[0].asList[42].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].lMuxChannelConnected	 = 	19
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].lRxChannelConnected	 = 	7
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].lADCChannelConnected	 = 	14
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].sCoilElementID.tElement	 = 	"H53"
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].sCoilElementID.ulUniqueKey	 = 	-248930358
sCoilSelectMeas.aRxCoilSelectData[0].asList[43].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].lMuxChannelConnected	 = 	19
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].lRxChannelConnected	 = 	7
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].lADCChannelConnected	 = 	13
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].sCoilElementID.tElement	 = 	"H54"
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].sCoilElementID.ulUniqueKey	 = 	1124680666
sCoilSelectMeas.aRxCoilSelectData[0].asList[44].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].lMuxChannelConnected	 = 	20
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].lRxChannelConnected	 = 	8
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].lADCChannelConnected	 = 	16
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].sCoilElementID.tElement	 = 	"H70"
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].sCoilElementID.ulUniqueKey	 = 	-79608815
sCoilSelectMeas.aRxCoilSelectData[0].asList[45].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].lMuxChannelConnected	 = 	20
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].lRxChannelConnected	 = 	8
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].lADCChannelConnected	 = 	15
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].sCoilElementID.tElement	 = 	"H50"
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].sCoilElementID.ulUniqueKey	 = 	-1232476902
sCoilSelectMeas.aRxCoilSelectData[0].asList[46].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].lMuxChannelConnected	 = 	21
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].lRxChannelConnected	 = 	9
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].lADCChannelConnected	 = 	17
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].sCoilElementID.tElement	 = 	"H71"
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].sCoilElementID.ulUniqueKey	 = 	-970887775
sCoilSelectMeas.aRxCoilSelectData[0].asList[47].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].lMuxChannelConnected	 = 	64
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].lRxChannelConnected	 = 	26
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].lADCChannelConnected	 = 	52
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].sCoilElementID.tElement	 = 	"H49"
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].sCoilElementID.ulUniqueKey	 = 	1891980494
sCoilSelectMeas.aRxCoilSelectData[0].asList[48].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].lMuxChannelConnected	 = 	51
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].lRxChannelConnected	 = 	15
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].lADCChannelConnected	 = 	29
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].sCoilElementID.tElement	 = 	"H40"
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].sCoilElementID.ulUniqueKey	 = 	2111125183
sCoilSelectMeas.aRxCoilSelectData[0].asList[49].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].lMuxChannelConnected	 = 	51
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].lRxChannelConnected	 = 	15
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].lADCChannelConnected	 = 	30
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].sCoilElementID.tElement	 = 	"H41"
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].sCoilElementID.ulUniqueKey	 = 	1085611791
sCoilSelectMeas.aRxCoilSelectData[0].asList[50].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].lMuxChannelConnected	 = 	52
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].lRxChannelConnected	 = 	16
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].lADCChannelConnected	 = 	31
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].sCoilElementID.tElement	 = 	"H42"
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].sCoilElementID.ulUniqueKey	 = 	118842847
sCoilSelectMeas.aRxCoilSelectData[0].asList[51].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].lMuxChannelConnected	 = 	52
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].lRxChannelConnected	 = 	16
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].lADCChannelConnected	 = 	32
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].sCoilElementID.tElement	 = 	"H43"
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].sCoilElementID.ulUniqueKey	 = 	980765807
sCoilSelectMeas.aRxCoilSelectData[0].asList[52].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].lMuxChannelConnected	 = 	62
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].lRxChannelConnected	 = 	24
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].lADCChannelConnected	 = 	48
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].sCoilElementID.tElement	 = 	"H44"
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].sCoilElementID.ulUniqueKey	 = 	-2007658369
sCoilSelectMeas.aRxCoilSelectData[0].asList[53].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].lMuxChannelConnected	 = 	62
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].lRxChannelConnected	 = 	24
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].lADCChannelConnected	 = 	47
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].sCoilElementID.tElement	 = 	"H45"
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].sCoilElementID.ulUniqueKey	 = 	-1254770225
sCoilSelectMeas.aRxCoilSelectData[0].asList[54].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].lMuxChannelConnected	 = 	63
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].lRxChannelConnected	 = 	25
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].lADCChannelConnected	 = 	49
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].sCoilElementID.tElement	 = 	"H46"
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].sCoilElementID.ulUniqueKey	 = 	-225066209
sCoilSelectMeas.aRxCoilSelectData[0].asList[55].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].lMuxChannelConnected	 = 	63
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].lRxChannelConnected	 = 	25
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].lADCChannelConnected	 = 	50
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].sCoilElementID.tElement	 = 	"H47"
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].sCoilElementID.ulUniqueKey	 = 	-805967185
sCoilSelectMeas.aRxCoilSelectData[0].asList[56].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].lMuxChannelConnected	 = 	64
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].lRxChannelConnected	 = 	26
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].lADCChannelConnected	 = 	51
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].sCoilElementID.tElement	 = 	"H48"
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].sCoilElementID.ulUniqueKey	 = 	1302691198
sCoilSelectMeas.aRxCoilSelectData[0].asList[57].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].lMuxChannelConnected	 = 	15
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].lRxChannelConnected	 = 	3
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].lADCChannelConnected	 = 	6
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].sCoilElementID.tElement	 = 	"H30"
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].sCoilElementID.tCoilClass	 = 	"Head_Rx"
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].sCoilElementID.ulUniqueKey	 = 	1624245767
sCoilSelectMeas.aRxCoilSelectData[0].asList[58].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].lMuxChannelConnected	 = 	15
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].lRxChannelConnected	 = 	3
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].lADCChannelConnected	 = 	5
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].sCoilElementID.tElement	 = 	"H31"
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].sCoilElementID.ulUniqueKey	 = 	1571827639
sCoilSelectMeas.aRxCoilSelectData[0].asList[59].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].lMuxChannelConnected	 = 	16
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].lRxChannelConnected	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].lADCChannelConnected	 = 	8
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].sCoilElementID.tElement	 = 	"H32"
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].sCoilElementID.ulUniqueKey	 = 	437278055
sCoilSelectMeas.aRxCoilSelectData[0].asList[60].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].lMuxChannelConnected	 = 	16
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].lRxChannelConnected	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].lADCChannelConnected	 = 	7
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].sCoilElementID.tElement	 = 	"H33"
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].sCoilElementID.ulUniqueKey	 = 	661683415
sCoilSelectMeas.aRxCoilSelectData[0].asList[61].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].lMuxChannelConnected	 = 	17
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].lRxChannelConnected	 = 	5
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].lADCChannelConnected	 = 	10
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].sCoilElementID.tElement	 = 	"H34"
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].sCoilElementID.ulUniqueKey	 = 	-1789878073
sCoilSelectMeas.aRxCoilSelectData[0].asList[62].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].lElementSelected	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].lMuxChannelConnected	 = 	17
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].lRxChannelConnected	 = 	5
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].lADCChannelConnected	 = 	9
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].sCoilElementID.tElement	 = 	"H35"
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].sCoilElementID.ulUniqueKey	 = 	-1473214089
sCoilSelectMeas.aRxCoilSelectData[0].asList[63].sCoilProperties.eCoilType	 = 	4
sCoilSelectMeas.aRxCoilSelectData[0].aFFT_SCALE.__attribute__.size	 = 	64
sCoilSelectMeas.aRxCoilSelectData[1].IgnoreCoilGroups	 = 	0x0
sCoilSelectMeas.aRxCoilSelectData[1].BCCombineMode	 = 	1
sCoilSelectMeas.aRxCoilSelectData[1].bSuppressMandatoryProperties	 = 	0x0
sCoilSelectMeas.aRxCoilSelectData[1].bIgnoreBCLCExcluding	 = 	0x0
sCoilSelectMeas.aRxCoilSelectData[1].bSuppressExclusiveProperties	 = 	0x0
sCoilSelectMeas.aRxCoilSelectData[1].BCCombineMatrix.__attribute__.size	 = 	0
sCoilSelectMeas.aRxCoilSelectData[1].asList.__attribute__.size	 = 	8
sCoilSelectMeas.aRxCoilSelectData[1].aFFT_SCALE.__attribute__.size	 = 	8
sCoilSelectMeas.aTxCoilSelectData.__attribute__.size	 = 	2
sCoilSelectMeas.aTxCoilSelectData[0].tNucleus	 = 	"1H"
sCoilSelectMeas.aTxCoilSelectData[0].tCheckUUID	 = 	"d56590fafbbcd0e4b810aaf062040aee8e70a47b"
sCoilSelectMeas.aTxCoilSelectData[0].asList.__attribute__.size	 = 	32
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].lElementSelected	 = 	1
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sCoilElementID.tCoilID	 = 	"Body"
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sCoilElementID.tElement	 = 	"BC0"
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sCoilElementID.tCoilClass	 = 	"BC"
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sCoilElementID.ulUniqueKey	 = 	-1604150962
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sTxScaleFactorCP.dRe	 = 	0.7071
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sTxScaleFactorEP.dRe	 = 	0.4752
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sCoilProperties.eCoilType	 = 	1
sCoilSelectMeas.aTxCoilSelectData[0].asList[0].sCoilProperties.tCoilManufacturer	 = 	"Siemens"
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].lElementSelected	 = 	1
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].lTxChannelConnected	 = 	1
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sCoilElementID.tCoilID	 = 	"Body"
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sCoilElementID.tElement	 = 	"BC1"
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sCoilElementID.ulUniqueKey	 = 	-1660768002
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sTxScaleFactorCP.dIm	 = 	0.7071
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sTxScaleFactorEP.dRe	 = 	-0.566
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sTxScaleFactorEP.dIm	 = 	0.6743
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sCoilProperties.eCoilType	 = 	1
sCoilSelectMeas.aTxCoilSelectData[0].asList[1].sCoilProperties.tCoilManufacturer	 = 	"Siemens"
sCoilSelectMeas.aTxCoilSelectData[1].asList.__attribute__.size	 = 	32
sCoilSelectMeas.aLocalShimCoilSelectData.__attribute__.size	 = 	1
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList.__attribute__.size	 = 	8
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[0].lElementSelected	 = 	1
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[0].lInputChannelConnected	 = 	13
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[0].lOutputChannelConnected	 = 	1
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[0].lLocalShimChannelConnected	 = 	1
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[0].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[0].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[0].sCoilElementID.tElement	 = 	"LS1"
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[0].sCoilElementID.ulUniqueKey	 = 	-1593113346
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[1].lElementSelected	 = 	1
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[1].lInputChannelConnected	 = 	14
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[1].lOutputChannelConnected	 = 	2
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[1].lLocalShimChannelConnected	 = 	2
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[1].sCoilElementID.tCoilID	 = 	"HeadNeck_64_CS"
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[1].sCoilElementID.lCoilCopy	 = 	1
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[1].sCoilElementID.tElement	 = 	"LS2"
sCoilSelectMeas.aLocalShimCoilSelectData[0].asList[1].sCoilElementID.ulUniqueKey	 = 	-424968658
sCoilSelectMeas.CoilPlugs.Plug.__attribute__.size	 = 	11
sCoilSelectMeas.CoilPlugs.Plug[0].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[0].IdPart[0]	 = 	255
sCoilSelectMeas.CoilPlugs.Plug[1].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[2].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[2].IdPart[0]	 = 	4889
sCoilSelectMeas.CoilPlugs.Plug[3].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[4].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[5].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[5].IdPart[0]	 = 	4887
sCoilSelectMeas.CoilPlugs.Plug[6].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[6].IdPart[0]	 = 	4888
sCoilSelectMeas.CoilPlugs.Plug[7].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[8].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[9].IdPart.__attribute__.size	 = 	8
sCoilSelectMeas.CoilPlugs.Plug[10].IdPart.__attribute__.size	 = 	8
sWipMemBlock.alFree.__attribute__.size	 = 	64
sWipMemBlock.alFree[3]	 = 	1
sWipMemBlock.alFree[4]	 = 	1
sWipMemBlock.alFree[63]	 = 	12345
sWipMemBlock.adFree.__attribute__.size	 = 	16
sWipMemBlock.adRes.__attribute__.size	 = 	3
ucBOLDParadigmArray.__attribute__.size	 = 	256
sParametricMapping.ucParametricMap	 = 	1
sParametricMapping.SimulatedTEArray.__attribute__.size	 = 	20
sIR.alMagicID.__attribute__.size	 = 	2
sIR.alFree.__attribute__.size	 = 	16
sIR.adFree.__attribute__.size	 = 	16
sAsl.ulMode	 = 	1
sAsl.ulSuppressionMode	 = 	1
sAsl.sPostLabelingDelay.__attribute__.size	 = 	64
sInversionArray.asElm.__attribute__.size	 = 	4
sWorkflow.eConflictSolverStrategy	 = 	1
sWorkflow.ucDotVoiceSettingsOverride	 = 	0x1
sWorkflow.ucDotPauseSettingsOverride	 = 	0x1
sWorkflow.alConflictSolverData.__attribute__.size	 = 	0
sWorkflow.adConflictSolverData.__attribute__.size	 = 	0
sDynDistCorrFilter.ucMode	 = 	1
sChannelMatrix.ucChannelMixingMode	 = 	1
sChannelMatrix.ucChannelDiscardMode	 = 	1
sPTXData.uiPTXTargetMagMode	 = 	1
sPTXData.sPTXMPRSliceArray.asSlice.__attribute__.size	 = 	256
sPTXData.sPTXMPRSliceArray.alSliceAcqOrder.__attribute__.size	 = 	256
sPTXData.sPTXMPRSliceArray.anAsc.__attribute__.size	 = 	256
sPTXData.sPTXMPRSliceArray.anPos.__attribute__.size	 = 	256
sPTXData.sPTXMPRSliceArray.sTSat.ulShape	 = 	1
sPTXData.sPTXMPRGroupArray.asGroup.__attribute__.size	 = 	256
sPTXData.sPTXMPRGroupArray.anMember.__attribute__.size	 = 	258
sPTXData.sPTXMPRGroupArray.sPSat.ulShape	 = 	1
sPTXData.asPTXVolume.__attribute__.size	 = 	0
sInlineCardioEval.lInlineEvaMode	 = 	1
sInlineCardioEval.lNoOfPreps	 = 	1
sInlineCardioEval.alRecoveryDuration.__attribute__.size	 = 	1
sInlineCardioEval.alRecoveryDuration[0]	 = 	1
sInlineCardioEval.alSamplingDuration.__attribute__.size	 = 	1
sInlineCardioEval.alSamplingDuration[0]	 = 	1
sInteractive.ucTracking	 = 	0x0
sInteractive.ucSliceFollowing	 = 	1
sInteractive.ucSliceFollowingMode	 = 	1
sInteractive.lTrackingBackgroundSuppr	 = 	5
sInteractive.lTrackingSensitivity	 = 	1
sInteractive.lTrackingFlipAngle	 = 	10
sInteractive.ucPause	 = 	0x0
sInteractive.ucMosaic	 = 	0x0
sInteractive.ucSkipPhysioTrigger	 = 	0x0
sInteractive.lDephasingGradients	 = 	0
sInteractive.ucTrackingOnly	 = 	0x0
sInteractive.lTrackingDeviceIndex	 = 	0
sInteractive.alDephasingGradientAngle.__attribute__.size	 = 	32
sDixonData.ucDixonEvaluation	 = 	0x0
sDixonData.sMrDixonOptions.ucDixonFat	 = 	0x0
sDixonData.sMrDixonOptions.ucDixonWater	 = 	0x0
sDixonData.sMrDixonOptions.ucDixonInPhase	 = 	0x0
sDixonData.sMrDixonOptions.ucDixonOpposedPhase	 = 	0x0
sDixonData.sMrDixonOptions.ucDixonOriginalEchoes	 = 	0x1
sDixonData.sMrDixonEvaluationOptions.ucDixonEvaWaterFraction	 = 	0x0
sDixonData.sMrDixonEvaluationOptions.ucDixonEvaFatFraction	 = 	0x0
sDixonData.sMrDixonEvaluationOptions.ucDixonEvaT2Star	 = 	0x0
sDixonData.sMrDixonEvaluationOptions.ucDixonEvaR2Star	 = 	0x0
sDixonData.sMrDixonEvaluationOptions.ucDixonEvaReport	 = 	0x0
asDynamicAdjustVolumes.__attribute__.size	 = 	0
sCommonIterRecon.lIterations	 = 	30
sCommonIterRecon.eReconMethod	 = 	1
sCommonIterRecon.dRegularization	 = 	9.99999974738e-06
sCommonIterRecon.eDenoisingMode	 = 	1
sCommonIterRecon.lDenoisingStrength	 = 	5
sCommonIterRecon.dScalingFactor	 = 	0.0
sCommonIterRecon.dTemporalScaleFactor	 = 	5.0
sCommonIterRecon.dThresholdWavelet	 = 	0.00700000021607
sCommonIterRecon.dTolerance	 = 	9.99999974738e-06
sCommonIterRecon.sGRASPData.lNumPhases	 = 	2
sCommonIterRecon.sGRASPData.ucPreview	 = 	0x0
sCommonIterRecon.sGRASPData.ucLiverAutoBolusDetection	 = 	0x0
sCommonIterRecon.sGRASPData.eWorkflow	 = 	1
sCommonIterRecon.sGRASPData.ucLiverGating	 = 	0x0
sCommonIterRecon.sGRASPData.eRedNumberReconVolumes	 = 	1
sCommonIterRecon.sGRASPData.dBolusDelay	 = 	5.0
sCommonIterRecon.sGRASPData.adDuration.__attribute__.size	 = 	2
sCommonIterRecon.sGRASPData.adDuration[0]	 = 	1.0
sCommonIterRecon.sGRASPData.adDuration[1]	 = 	1.0
sCommonIterRecon.sGRASPData.adTemporalResolution.__attribute__.size	 = 	2
sCommonIterRecon.sGRASPData.alReconstructedVolumes.__attribute__.size	 = 	2
sCommonIterRecon.sGRASPData.alReconstructedVolumes[0]	 = 	1
sCommonIterRecon.sGRASPData.alReconstructedVolumes[1]	 = 	1
sSliceAcceleration.lMultiBandFactor	 = 	1
sSliceAcceleration.lFOVShiftFactor	 = 	1
MrFingerprinting.MrfMode	 = 	1
MrFingerprinting.MrfUserMode	 = 	0
MrFingerprinting.MrfDictUUID.__attribute__.size	 = 	16
MrAdvancedReconstruction.lAdvancedReconstructionMode	 = 	1
MrAdvancedReconstruction.lDenoisingMethod	 = 	0
MrAdvancedReconstruction.sDeepResolveGain.lDenoisingStrength	 = 	3
MrAdvancedReconstruction.sDeepResolveGain.lEdgeEnhancementStrength	 = 	3
MrAdvancedReconstruction.sDeepResolveGain.ucEdgeEnhancementOn	 = 	0x1
MrAdvancedReconstruction.sDeepResolveBoost.lDenoisingStrength	 = 	2
### ASCCONV END ###
